
version: 2

models:
    - name: consumer_order_analytics
      description: "A sample on how to reference a model from another project"
      columns:
          - name: order_id
            description: "The order identifier"
            tests:
                - not_null
