version: 2

sources:
  - name: edw_staging
    database: colint_demo  # Replace with your actual database name
    schema: dbt_spoke_cthornburg # edw_staging  
    tables:
      - name: cur_mdm_c_b_addr
      - name: cur_loc_gpstore  
      - name: CUR_CUS_DBARCUD
      - name: CUR_CUS_MASTER 
      - name: CUR_CUS_BLC_ADDRESS
      - name: CUR_CUS_ORW_CUSTOMER_ADDRESS

  - name: hub_load
    database: colint_demo  # Replace with your actual database name
    schema: dbt_spoke_cthornburg # hub_load_schema  
    tables:
      - name: dim_geography